import type { SortOrder } from "../types";

/**
 * Every piece of text the v3.0 screens show or announce, in one place — ready for translation
 * (v4.1) without hunting through components. Accessible names the robot tests find controls
 * by live here too, so renaming one is a visible, single-line change.
 */
export const strings = {
    appName: "Tab Sandwich",
    searchLabel: "Search saved tabs",
    searchPlaceholder: (count: number) => `Search ${count} saved tab${count === 1 ? "" : "s"}`,
    searchArchivePlaceholder: (count: number) => `Search ${count} archived tab${count === 1 ? "" : "s"}`,
    clearSearch: "Clear search",
    matches: (count: number) => (count === 0 ? "No matching tabs" : `${count} matching tab${count === 1 ? "" : "s"}`),
    addLinkManually: "Add link manually",
    openSettings: "Open settings",
    settingsTooltip: "Settings",

    currentTab: "Current tab",
    saveTab: "Save Tab",
    save: "Save",
    saved: "Saved!",
    alreadySaved: "Already saved",
    // The save card on a page that's already saved.
    savedAgo: (days: number) => (days <= 0 ? "Saved today" : days === 1 ? "Saved yesterday" : `Saved ${days} days ago`),
    show: "Show",
    showTooltip: "Show it in the list",
    update: "Update",
    updateTooltip: "Update the saved copy: this page's title and address, today's date, and the category picked here",
    updatedButton: "Updated!",
    updatedToast: "Updated",
    categoryOfSaved: "Saved in category",
    open: "Open",
    openSavedTooltip: "Open the saved link in a new tab",
    onlyWebPages: "Only web pages can be saved",
    // Saving a whole window, under the save card.
    saveWindowAll: (count: number) => `Save all ${count} tabs in this window`,
    saveWindowNew: (count: number) => `Save ${count} new tab${count === 1 ? "" : "s"} from this window`,
    saveWindowTooltip: "Saves every web page open in this window into the category picked above (Uncategorized when the page you're on is already saved). Pages you've already saved are skipped.",
    savingWindow: "Saving…",
    windowSaved: (count: number) => (count === 0 ? "Nothing new to save" : `Saved ${count} tab${count === 1 ? "" : "s"}`),
    windowSkippedCount: (count: number) => `${count} skipped`,
    windowSkipped: (alreadySaved: number, browserPages: number) =>
        [
            alreadySaved > 0 && `${alreadySaved} already saved`,
            browserPages > 0 && `${browserPages} browser page${browserPages === 1 ? "" : "s"}`,
        ]
            .filter(Boolean)
            .join(", "),
    closeTabs: (count: number) => `Close ${count} tab${count === 1 ? "" : "s"}`,
    closeTabsTooltip: "Close the saved tabs in this window. The tab you're on stays open.",
    closedTabs: (count: number) => `Closed ${count} tab${count === 1 ? "" : "s"}`,
    windowDenied: "Nothing saved. Saving a window needs your OK to see its tabs.",
    tryAgain: "Try again",
    saveToCategory: "Save to category",

    addLinkTitle: "Add a link by hand",
    urlLabel: "URL",
    urlPlaceholder: "Paste a link, like https://example.com",
    titleOptionalLabel: "Title (optional)",
    categoryOptionalLabel: "Category (optional)",
    add: "Add",
    cancel: "Cancel",
    enterValidUrl: "Enter a valid URL",

    filterBarLabel: "Filter and sort saved tabs",
    filterLabel: "Filter saved tabs",
    all: "All",
    outdated: "Waiting",
    outdatedPill: (count: number) => `Waiting (${count})`,
    archived: "Archived",
    archivedPill: (count: number) => `Archived (${count})`,

    sortButton: (choice: string) => `Sort: ${choice}`,
    sortMenuLabel: "Sort saved tabs",
    /** The menu's full wording. */
    sortOptions: {
        custom: "Your order",
        newest: "Newest first",
        oldest: "Oldest first",
        title: "Title (A–Z)",
        site: "Site (A–Z)",
        opened: "Recently opened",
        openedMost: "Most opened",
    } as Record<SortOrder, string>,
    /** The short form the button shows while a sort other than your own order is on. */
    sortShort: { custom: "Your order", newest: "Newest", oldest: "Oldest", title: "Title", site: "Site", opened: "Opened", openedMost: "Most opened" } as Record<SortOrder, string>,

    storageNearlyFull: (pct: number) => `Storage is ${pct}% full.`,
    seeStorage: "See storage",

    savedTabsLabel: "Saved tabs",
    // The list with nothing to show: first run (or everything deleted), and a search with no results.
    emptyTitle: "Nothing saved yet",
    emptyLead: "Tabs you save land here, ready for when you need them.",
    emptyTipsLabel: "Getting started",
    tipSave: "Save the page you're on: pick a category above, then press Save.",
    tipShortcut: "Open Tab Sandwich from anywhere with",
    tipShortcutUnset: "Open Tab Sandwich from anywhere with a keyboard shortcut.",
    setShortcut: "Set one",
    tipCategories: "Make the categories yours.",
    editCategories: "Edit categories",
    noMatchesTitle: (query: string) => `No saved tabs match “${query}”`,
    noMatchesHint: "Search looks at titles, sites, categories and saved windows. Try fewer letters, or part of a name.",
    noMatchesInFilter: (filter: string) => `Only tabs in ${filter} were searched.`,
    searchAllTabs: "Search all tabs",

    // "What's new": one note per feature release, shown once after updating (see domain/whatsNew.ts).
    whatsNewTitle: (release: string) => `New in ${release}`,
    dismissWhatsNew: "Dismiss what's new",
    whatsNewNotes: {
        "3.2": [
            "Save every tab in a window at once, then close them in one click.",
            "A saved window stays together as one row, named like “Toasted Rye”.",
            "Select several tabs to move or delete them together.",
        ],
        "3.1": [
            "Sort your list by newest, oldest, title or site.",
            "A page you've already saved says so, with Show and Update.",
            "Everything works from the keyboard. The keys are in Settings › General.",
        ],
    } as Record<string, readonly string[]>,
    categoryForScreenReaders: (category: string) => `Category: ${category}`,
    pinTab: (title: string) => `Pin ${title}`,
    archiveTab: (title: string) => `Archive ${title}`,
    archiveTooltip: "Archive (Delete)",
    archivedToast: "Archived",
    restoreTab: (title: string) => `Restore ${title}`,
    restoreTooltip: "Back to your list",
    restoredToast: "Restored",
    deleteForeverTab: (title: string) => `Delete ${title} for good`,
    deleteForeverTooltip: "Delete for good (Delete)",
    cantMoveArchived: "Restore a tab to move it.",
    allArchivedTitle: "Everything's in the archive",
    allArchivedBody: "Archived tabs leave the list but stay saved, ready to restore.",
    showArchive: "Show the archive",
    searchArchive: "Search the archive",
    unpinTab: (title: string) => `Unpin ${title}`,
    pinTooltip: "Pin to the top (P)",
    unpinTooltip: "Unpin (P)",
    /** Read with a pinned row (the pin on screen shows it). */
    pinnedForScreenReaders: "Pinned",
    pinnedNote: (title: string) => `Pinned “${title}” to the top`,
    unpinnedNote: (title: string) => `Unpinned “${title}”`,
    /** Read before a search result's saved window name (the stack icon shows it on screen). */
    inSavedWindow: "Saved window:",
    savedDaysAgo: (days: number) => `Saved ${days} day${days === 1 ? "" : "s"} ago`,
    ageBadge: (days: number) => `${days}d`,
    // Choosing several tabs at once.
    selectTabs: "Select tabs",
    selectTooltip: "Select several tabs, to move or delete them together",
    selectedCount: (count: number) => (count === 0 ? "None selected" : `${count} selected`),
    selectAll: "Select all",
    selectAllTooltip: "Select every tab shown, including the tabs in saved windows",
    moveTo: "Move to…",
    moveToLabel: "Move the selected tabs to a category",
    deleteSelectedLabel: (count: number) => `Delete ${count} selected tab${count === 1 ? "" : "s"} for good`,
    archiveSelectedLabel: (count: number) => `Archive ${count} selected tab${count === 1 ? "" : "s"}`,
    restoreSelectedLabel: (count: number) => `Restore ${count} selected tab${count === 1 ? "" : "s"}`,
    restoreSelected: "Restore",
    stopSelecting: "Stop selecting",
    stopSelectingTooltip: "Stop selecting (Esc)",
    selectionBarLabel: "Selected tabs",
    selectWindow: (name: string) => `Select every tab in ${name}`,
    toggleWindow: "Open or close this saved window",
    movedTabs: (count: number, category: string) => `Moved ${count} tab${count === 1 ? "" : "s"} to ${category}`,
    deletedTabs: (count: number) => `Deleted ${count} tab${count === 1 ? "" : "s"}`,
    archivedTabs: (count: number) => `Archived ${count} tab${count === 1 ? "" : "s"}`,
    restoredTabs: (count: number) => `Restored ${count} tab${count === 1 ? "" : "s"}`,
    archiveAllWaiting: (count: number) => `Archive all ${count} waiting tab${count === 1 ? "" : "s"}`,
    cleanupTip: (count: number) => `${count} kept tab${count === 1 ? "" : "s"} not opened in 6 months`,
    cleanupArchive: "Archive them",
    cleanupNotNow: "Not now",
    archiveAllWaitingHint: "Still saved: restore any of them from Archived.",

    // Saved windows (groups) in the list.
    /**
     * A saved window is named at random from these, sandwich-style ("Toasted Rye"): a name that
     * belongs to no one tab in it. Its count and date are shown beside it, worked out live.
     */
    groupNameWords: {
        adjectives: ["Toasted", "Crispy", "Golden", "Buttery", "Warm", "Crusty", "Fluffy", "Grilled", "Melty", "Savory", "Zesty", "Tangy",
            "Smoky", "Honeyed", "Peppery", "Herby", "Sunny", "Rustic", "Hearty", "Flaky", "Spicy", "Fresh", "Cozy", "Seeded"],
        nouns: ["Rye", "Bagel", "Panini", "Baguette", "Ciabatta", "Brioche", "Croissant", "Focaccia", "Pretzel", "Sourdough", "Muffin", "Pita",
            "Wrap", "Club", "Reuben", "Toastie", "Melt", "Hoagie", "Bun", "Crumpet", "Biscuit", "Flatbread", "Roll", "Loaf", "Pickle",
            "Cheddar", "Pesto", "Avocado", "Tomato", "Mustard"],
    },
    groupTabCount: (count: number) => `${count} tabs`,
    /** When a window was saved: "6 Oct", with the year once it isn't this year's. */
    groupSavedOn: (date: Date) =>
        new Intl.DateTimeFormat(undefined, {
            day: "numeric",
            month: "short",
            year: date.getFullYear() === new Date().getFullYear() ? undefined : "numeric",
        }).format(date),
    groupMore: (count: number) => `+${count}`,
    groupActions: (name: string) => `Actions for ${name}`,
    groupActionsTooltip: "Open, rename, break apart or archive",
    openGroup: "Open all in a new window",
    openGroupAndRemove: "Open all and archive them",
    renameGroup: "Rename",
    groupNameLabel: "Saved window name",
    ungroup: "Break apart",
    // "Remove", not "Delete": it's about the list, and closes nothing in the browser.
    archiveGroup: "Archive",
    groupArchived: (count: number) => `Archived ${count} tabs`,
    groupBrokenApart: "Broken apart",
    groupOpened: (count: number) => `Opened ${count} tabs and archived them`,
    editTab: (title: string) => `Edit ${title}`,
    deleteTab: (title: string) => `Delete ${title}`,
    editTooltip: "Edit",
    deleteTooltip: "Delete",

    titleLabel: "Title",
    noteLabel: "Note",
    notePlaceholder: "Why you saved it (optional)",
    addNote: "Add a note",
    titlePlaceholder: "Title",
    categoryLabel: "Category",
    editUrlPlaceholder: "https://example.com",
    enterValidUrlSentence: "Enter a valid URL.",
    alreadySavedAs: (title: string) => `Already saved as “${title}”.`,
    archivedAs: (title: string) => `In your archive, as “${title}”.`,
    inYourArchive: "In your archive",
    restore: "Restore",
    restoreSavedTooltip: "Bring it back to your list",

    // Keyboard control of the list (stage 4 of v3.1).
    movedTo: (title: string, position: number, total: number) => `Moved “${title}” to position ${position} of ${total}`,
    movedOutOf: (name: string) => `Moved out of ${name}`,
    movedInto: (name: string) => `Moved into ${name}`,
    /** Read out after Alt+arrows steps a tab out of its saved window. */
    steppedOutOf: (title: string, name: string) => `Moved “${title}” out of ${name}`,
    cantMoveSorted: "Tabs can only be moved in your own order. Switch the sort to Your order first.",
    cantMoveSearching: "Clear the search to move tabs.",
    pinLine: (pinned: boolean) =>
        pinned ? "Pinned tabs stay above the others. Press P to unpin it." : "Pinned tabs stay above the others. Press P to pin this one.",
    keyboardKeys: "Keys in the list",
    keyHelp: {
        search: "Jump to search",
        move: "Move through your saved tabs",
        open: "Open the tab",
        window: "Open or close a saved window",
        select: "Select or unselect, while selecting",
        edit: "Edit it",
        pin: "Pin it to the top, or unpin it",
        delete: "Delete it",
        undo: "Undo, while Undo is showing",
        reorder: "Move it up or down (in your own order)",
        back: "Back to search",
    },
    deleted: "Deleted",
    undo: "Undo",
    upgradeFailed: "Couldn't update your saved data for this version. Nothing was changed.",

    // Settings
    settingsTitle: "Settings",
    back: "Back",
    settingsSections: "Settings sections",
    tabGeneral: "General",
    tabCategories: "Categories",
    tabBackup: "Backup",
    tabAbout: "About",

    appearance: "Appearance",
    themeGroup: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    themeHint: "System follows your computer's light or dark setting, even while the popup is open.",
    keyboardShortcut: "Keyboard shortcut",
    shortcutNotSet: "Not set",
    customize: "Customize",
    storage: "Storage",
    storageUsed: "Storage used",
    storageSummary: (count: number, pct: number) =>
        `${count} saved · ${pct < 1 ? "less than 1%" : `${Math.round(pct)}%`} of the space Chrome gives extensions`,
    storageAdvice: "Export a backup, then remove tabs you no longer need.",

    newCategory: "New category",
    configuredCategories: "Configured categories",
    colorFor: (name: string) => `Color for ${name}`,
    renameCategory: (name: string) => `Rename ${name}`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    removeCategory: (name: string) => `Remove ${name}`,
    tabCount: (count: number) => `${count} tab${count === 1 ? "" : "s"}`,
    /** The moon on a category's row: lit = its tabs age and show as waiting; dim = kept. */
    waitingToggle: (name: string) => `Waiting reminder for ${name}`,
    waitingOnTitle: (days: number) => `Its tabs show as waiting after ${days} day${days === 1 ? "" : "s"}`,
    waitingOffTitle: "Kept: its tabs never show as waiting",
    waitingAfter: "Show as waiting after",
    waitingAfterHint: "Only tabs in categories with the moon lit; the others are kept.",
    days: "days",
    renameRefusal: {
        empty: "Name can't be empty.",
        gone: "Category no longer exists.",
        taken: "That name is already used by another category.",
    },
    removeRefusal: {
        reserved: '"Uncategorized" can\'t be removed.',
        "in-use": "In use — reassign its tabs first.",
        archived: "Tabs in your archive still use it — delete them there first.",
    },
    storageFull: "Storage is full. Export your tabs, remove some, then try again.",
    couldntSave: "Couldn't save your changes. Try again.",
    colorNames: {
        purple: "Purple",
        coral: "Coral",
        teal: "Teal",
        pink: "Pink",
        amber: "Amber",
        blue: "Blue",
        green: "Green",
        slate: "Slate",
        sand: "Sand",
    } as Record<string, string>,

    backupTitle: "Backup",
    backupHint: "Export your saved tabs to a file, or import a previous backup.",
    exportBackup: "Export",
    importBackup: "Import",
    chooseBackupFile: "Choose a backup file to import",
    fileContains: (tabs: number) =>
        `This file contains ${tabs} tab${tabs === 1 ? "" : "s"}. Merge adds anything new; Replace overwrites everything currently saved.`,
    merge: "Merge",
    replaceAll: "Replace all",
    exported: (tabs: number) => `Exported ${tabs} tab${tabs === 1 ? "" : "s"}.`,
    nothingNew: "Nothing new — everything in this file is already saved.",
    imported: (tabs: number, categories: number) =>
        `Imported ${[
            tabs > 0 ? `${tabs} tab${tabs === 1 ? "" : "s"}` : "",
            categories > 0 ? `${categories} categor${categories === 1 ? "y" : "ies"}` : "",
        ]
            .filter(Boolean)
            .join(" and ")}`,
    replacedAll: "Replaced all tabs and settings",
    notABackup: "That file doesn't look like a Tab Sandwich backup.",

    version: (v: string) => `Version ${v}`,
    localPromise: "Everything stays in this browser. No account, no server, no analytics. Your tabs leave the browser only when you export them.",
    privacyPolicy: "Privacy policy",
    sourceCode: "Source code",
} as const;
